### ISSUE TITLE
Install Fails when installing electron

### ISSUE THREAD

**Issue by postables** [josselinchevalay/telescope#31]
```
> electron@1.6.8 postinstall /home/solidity/Documents/Code/telescope/node_modules/electron-prebuilt-compile/node_modules/electron
> node install.js

/home/solidity/Documents/Code/telescope/node_modules/electron-prebuilt-compile/node_modules/electron/install.js:47
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TLSWrap.onread (net.js:618:25)
npm WARN electron-app-ipfs@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/solidity/.npm/_logs/2018-06-22T20_43_52_589Z-debug.log
```

relevant section from debug log:
```
49384 warn electron-app-ipfs@1.0.0 No repository field.
49385 warn optional SKIPPING OPTIONAL DEPENDENCY: appdmg@0.4.5 (node_modules/appdmg):
49386 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
49387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
49387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
49387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
49387 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
49388 verbose stack Error: electron@1.6.8 postinstall: `node install.js`
49388 verbose stack Exit status 1
49388 verbose stack     at EventEmitter.<anonymous> (/usr/local/bin/nodejs/node-v8.11.2-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
49388 verbose stack     at emitTwo (events.js:126:13)
49388 verbose stack     at EventEmitter.emit (events.js:214:7)
49388 verbose stack     at ChildProcess.<anonymous> (/usr/local/bin/nodejs/node-v8.11.2-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
49388 verbose stack     at emitTwo (events.js:126:13)
49388 verbose stack     at ChildProcess.emit (events.js:214:7)
49388 verbose stack     at maybeClose (internal/child_process.js:925:16)
49388 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
49389 verbose pkgid electron@1.6.8
49390 verbose cwd /home/solidity/Documents/Code/telescope
49391 verbose Linux 4.13.0-45-generic
49392 verbose argv "/usr/local/bin/nodejs/node-v8.11.2-linux-x64/bin/node" "/usr/local/bin/npm" "install" "--only-dev"
49393 verbose node v8.11.2
49394 verbose npm  v5.6.0
49395 error code ELIFECYCLE
49396 error errno 1
49397 error electron@1.6.8 postinstall: `node install.js`
49397 error Exit status 1
49398 error Failed at the electron@1.6.8 postinstall script.
49398 error This is probably not a problem with npm. There is likely additional logging output above.
49399 verbose exit [ 1, true ]
```

**Comment by josselinchevalay** [comment]
which os do you use ?

**Comment by postables** [comment]
Ubuntu 16.04.4LTS

Like a system proxy? No I shouldn't, I have a minikube installation running on this laptop though.

**Comment by postables** [comment]
That did the trick, I was able to install however I got the following security vulnerability error:
```
npm WARN notice [SECURITY] electron has the following vulnerabilities: 1 critical, 2 high. Go here for more details: https://nodesecurity.io/advisories?search=electron&version=1.6.8 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> fs-xattr@0.1.17 install /home/solidity/Documents/Code/telescope/node_modules/fs-xattr
> node-gyp rebuild

make: Entering directory '/home/solidity/Documents/Code/telescope/node_modules/fs-xattr/build'
  CXX(target) Release/obj.target/xattr/src/async.o
../src/async.cc: In member function ‘virtual void XattrWorker::HandleErrorCallback()’:
../src/async.cc:35:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(1, argv);
                           ^
In file included from ../src/async.cc:2:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/async.cc: In member function ‘virtual void GetWorker::HandleOKCallback()’:
../src/async.cc:129:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/async.cc:2:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/async.cc: In member function ‘virtual void ListWorker::HandleOKCallback()’:
../src/async.cc:186:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     callback->Call(2, argv);
                           ^
In file included from ../src/async.cc:2:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/sync.o
  CXX(target) Release/obj.target/xattr/src/util.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/obj.target/xattr.node
  COPY Release/xattr.node
make: Leaving directory '/home/solidity/Documents/Code/telescope/node_modules/fs-xattr/build'

```
